<?php

/**
 * @file
 * Contains asu apartment search module.
 */

/**
 * Implements hook_theme().
 */
function asu_apartment_search_theme() {
  return [
    'asu_content' => [
      'variables' => [
        'cta_image' => NULL,
        'application_start_time' => NULL,
        'application_end_time' => NULL,
        'is_application_period_active' => NULL,
        'district' => NULL,
        'address' => NULL,
        'ownership_type' => NULL,
        'accessibility' => NULL,
        'project_description' => NULL,
        'building_type' => NULL,
        'energy_class' => NULL,
        'services' => NULL,
        'services_url' => NULL,
        'attachments' => NULL,
        'estimated_completion_date' => NULL,
      ],
    ],
  ];
}

/**
 *
 */
function asu_apartment_search_entity_load(array &$entities, string $entity_type) {
  if ($entity_type === 'menu_link_content') {
    foreach ($entities as $entity) {
      $disabled_routes = [
        'route:asu_apartment_search.haso_upcoming',
        'route:asu_apartment_search.hitas_upcoming',
      ];

      if (in_array($entity->get('link')->uri, $disabled_routes)) {
        $entity->delete();
      }
    }
  }
}
