<?php

/**
 * @file
 * Contains asu_translation.module.
 */

/**
 * Implements hook_form_alter().
 *   Updates translation files when ElasticSearch index is is updated.
 */
function asu_content_form_search_api_index_fields_alter() {
  /** @var \Drupal\asu_content\TranslationFileWriter $po_writer */
  $po_writer = \Drupal::service('asu_content.translation_file_writer');

  $index = Index::load('apartment');
  if ($index) {
    $fields = $index->getFields();

    if ($fields) {
      $po_writer->writePoFile($fields);
    }
  }
}

