popup_agree_button_message: Hyväksy
popup_more_info_button_message: 'Näytä evästeet'
popup_find_more_button_message: 'Näytä evästeet'
popup_hide_button_message: Piilossa
popup_info:
  value: '<h2>Hel.fi käyttää evästeitä</h2><p>Tämä sivusto käyttää välttämättömiä evästeitä suorituskyvyn varmistamiseksi sekä yleisen käytön seurantaan. Lisäksi käytämme kohdennusevästeitä käyttäjäkokemuksen parantamiseksi, analytiikkaan ja kohdistetun sisällön näyttämiseen.</p>'
disagree_button_label: 'Ei kiitos'
withdraw_tab_button_label: Tietosuoja-asetukset
save_preferences_button_label: 'Hyväksy valitut evästeet'
accept_all_categories_button_label: 'Hyväksy kaikki evästeet'
popup_agreed:
  value: "<h2>Kiitos että hyväksyit evästeet</h2>\r\n\r\n<p>Voit sulkea tämän viestin tai lukea lisää evästeistä.</p>\r\n"
withdraw_message:
  value: "<h2>Hel.fi käyttää evästeitä</h2>\r\n\r\n<p>Olet antanut hyväksynnän evästeiden asettamiseksi.</p>\r\n"
withdraw_action_button_label: 'Peruuta hyväksyntä'
