asu_noindex.settings:
  type: config_object
  label: "ASU Noindex settings"
  mapping:
    indexed_langs:
      type: sequence
      label: "Languages allowed to be indexed"
      sequence:
        type: string
