<?php

/**
 * @file
 * Contains asu_mailer.module.
 */

/**
 * Implements hook_mail().
 */
function asu_mailer_mail(string $key, array &$message, array $params) {
  switch ($key) {
    case 'application_user_confirmation':
      send_application_confirmation($message, $params);
      break;
  }
}

/**
 * Send confirmation mail to user after application has been created.
 *
 * @param array $message
 *   Message variable.
 * @param array $params
 *   Parameters variable.
 */
function send_application_confirmation(array &$message, array $params) {
  $message['from'] = \Drupal::config('system.site')->get('mail');
  $message['subject'] = $params['subject'];
  $message['body'][] = $params['message'];
}
