asu_application.create_application:
  path: '/admin/application/create/{user_id}/{project_id}'
  defaults:
    _title: 'Create application'
    _form: '\Drupal\asu_application\Form\SalespersonApplicationForm'
  requirements:
    _permission: 'administer content'
    _admin_route: 'true'
    no_cache: 'true'
