asu_application.admin_create_application:
  path: '/application/create/{user_id}'
  defaults:
    _title: 'Create application'
    _form: '\Drupal\asu_application\Form\SalespersonApplicationForm'
  requirements:
    _permission: 'administer applications'

asu_application.application_results:
  path: '/user/application/results'
  defaults:
    _controller: '\Drupal\asu_application\Controller\ResultController::getResults'
  methods: [POST]
  requirements:
    _permission: 'create application'

asu_application.lottery_start:
  path: '/lottery/start/{project_uuid}'
  defaults:
    _controller: '\Drupal\asu_application\Controller\ResultController::startLottery'
  methods: [GET]
  requirements:
    _permission: 'administer applications'
