hitas_application_created_subject_fi: 'Hitas-asuntohakemus luotu onnistuneesti.'
hitas_application_created_text_fi: "Hei\r\n\r\nOlemme vastaanottaneet hakemuksenne. "
haso_application_created_subject_fi: 'HASO-asuntohakemus luotu onnistuneesti.'
haso_application_created_text_fi: "Hei\r\n\r\nOlemme vastaanottaneet hakemuksenne."
hitas_application_created_subject_en: 'Thank you for the application.'
hitas_application_created_text_en: "Hello\r\n\r\nWe have received your application."
haso_application_created_subject_en: 'Thank you for the application.'
haso_application_created_text_en: "Hello\r\n\r\nWe have received your application."
