_core:
  default_config_hash: DlFPozYNOFuBqQVms526YfSXmbsKH-9c1-f4ZYJXDc0
iconset: social-icons--square
services:
  facebook: facebook
  x: x
  linkedin: linkedin
width: 24px
radius: 0px
print_css: ''
facebook_app_id: ''
node_field: false
