_core:
  default_config_hash: 6Ka3T1c-CIjEUO1Q64NXKksLthkMhj53a6zy4RJBtkc
langcode: en
verbose: 0
types:
  crop: {  }
  file: {  }
  menu_link_content: {  }
  node:
    '*': '*'
  paragraphs_library_item:
    '*': '*'
  path_alias: {  }
  redirect: {  }
  taxonomy_term:
    '*': '*'
  user: {  }
  paragraph: {  }
  media: {  }
  asu_application: {  }
  block_content: {  }
  contact_message: {  }
  contact_email: {  }
  search_api_task: {  }
types_translation_lock: {  }
types_js_lock: {  }
form_op_lock:
  crop:
    mode: 0
    values: {  }
  file:
    mode: null
    values: {  }
  menu_link_content:
    mode: 0
    values: {  }
  node:
    mode: 0
    values: {  }
  paragraphs_library_item:
    mode: 0
    values: {  }
  path_alias:
    mode: 0
    values: {  }
  redirect:
    mode: 0
    values: {  }
  taxonomy_term:
    mode: 0
    values: {  }
  user:
    mode: 0
    values: {  }
  paragraph:
    mode: 0
    values: {  }
  media:
    mode: 0
    values: {  }
  asu_application:
    mode: 0
    values: {  }
  block_content:
    mode: 0
    values: {  }
  contact_message:
    mode: 0
    values: {  }
  contact_email:
    mode: 0
    values: {  }
  search_api_task:
    mode: null
    values: {  }
