_core:
  default_config_hash: K2gkzwu6yIWvdJgOBpqqGsIB4ZKLNNMvAJsWn-v5iOI
langcode: en
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
logo:
  use_default: true
