_core:
  default_config_hash: AOXdYmkvKEWQ90i8bbStpi07jONjN29ny1BcgITQFSM
langcode: en
site_settings:
  default_icon: home-smoke
  theme_color: coat-of-arms
  koro: basic
footer_settings:
  footer_color: dark
