_core:
  default_config_hash: WMetmjQwIi1pjKuESDGJxM52cshpFeIifaq7NsDxw3Y
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
preset_accent_color: light_blue
preset_focus_color: gin
enable_darkmode: false
classic_toolbar: horizontal
high_contrast_mode: false
accent_color: ''
focus_color: ''
icon_default: true
icon_upload: ''
