_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: current
defaults:
  sender: test_mail_collector
  formatter: php_mail
modules:
  swiftmailer:
    none:
      sender: swiftmailer
      formatter: swiftmailer
