_core:
  default_config_hash: YpBA3MmDuJpZ9SM3DE4kR0lTY89bf2y3g0sS7s3TQ4k
langcode: en
always_save_userinfo: true
connect_existing_users: true
override_registration_settings: true
end_session_enabled: true
user_login_display: hidden
redirect_login: user
redirect_logout: ''
userinfo_mappings:
  timezone: zoneinfo
role_mappings:
  customer: {  }
  supervisor: {  }
  read_only: {  }
  content_producer: {  }
  editor: {  }
  salesperson: {  }
  admin: {  }
