_core:
  default_config_hash: 2fwxXOq3dbjiboKslfHTJXYWAk4u1zadK65SRiDrxug
registration: none
registration_ftll_expire: true
registration_ftll_timeout: 86400
notify:
  register_confirmation_with_pass: true
