<?php

/**
 * @file
 * Contains asu_user module.
 */

use Drupal\asu_user\Helper\StoreHelper;
use Drupal\Core\Url;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\asu_api\Api\BackendApi\Request\UpdateUserRequest;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\user\Entity\User;
use Drupal\user\UserInterface;
use Drupal\asu_api\Api\BackendApi\Request\UserRequest;
use Drupal\asu_api\Api\BackendApi\Request\CreateUserRequest;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_entity_type_alter().
 */
function asu_user_entity_type_alter(array &$entity_types) {
  $entity_types['user']->setFormClass('register', 'Drupal\asu_user\RegisterForm');
}

/**
 * Implements hook_user_login().
 */
function asu_user_user_login(UserInterface $account) {
  asu_create_backend_user($account);
  if ($account->hasRole('customer')) {
    asu_validate_email($account);
    asu_send_user_email_verification_reminder($account);
    asu_get_user_external_field_data($account);
    asu_redirect_on_login_by_session($account);
  }
}

/**
 * Implements hook_openid_connect_userinfo_save().
 *
 * After user has authenticated in profiili.
 * New backend profile is created based on that data.
 */
function asu_user_openid_connect_userinfo_save(UserInterface $account, array $context) {
  $helsinkiProfiiliUid = $context['userinfo']['sub'];
  $emailVerified = $context['userinfo']['email_verified'] ? 1 : 0;

  if ($context['is_new']) {
    $session = \Drupal::request()->getSession();
    $session->set('first_name', $context['userinfo']['given_name']);
    $session->set('last_name', $context['userinfo']['family_name']);

    $account->set('type', 'customer');
    $account->set('field_hel_profiili_uid', $helsinkiProfiiliUid);
    $account->set('field_email_is_valid', $emailVerified);
    $account->set('langcode', 'fi');
    $account->set('preferred_langcode', 'fi');
    $account->set('preferred_admin_langcode', 'fi');
    \Drupal::messenger()->addMessage(t('Thank you for registering. Please update your user information before proceeding.'));
  }
  else {
    $oldEmail = $account->getEmail();
    $newEmail = $context['userinfo']['email'];
    if ($oldEmail !== $newEmail) {
      $account->setEmail($newEmail);
      $account->set('field_email_is_valid', $emailVerified);
      \Drupal::messenger()->addMessage(t('Your email address has changed. You must verify your new email address before proceeding.'));
    }
  }
}

/**
 * Set email valid if user uses emailed login link.
 */
function asu_validate_email(UserInterface $account) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  $routes = ['user.login.http', 'user.reset.login'];
  // Set email_is_valid to true.
  if (in_array($route_name, $routes)) {
    if ($account->hasField('field_email_is_valid')) {
      $account->field_email_is_valid = 1;
      $account->save();
    }
  }
}

/**
 * Send user an email if email has not been validated by user.
 */
function asu_send_user_email_verification_reminder(UserInterface $account) {
  if ($account->field_email_is_valid->value == 0) {
    // Prevent sending email verification mail.
    $sendMail = $account->getLastAccessedTime() != 0 && (time() - $account->getCreatedTime() >= 86400);
    if ($sendMail) {
      asu_send_user_email('asu_email_approval_required', $account);
    }
  }
}

/**
 * Make sure user has an existing account in backend.
 */
function asu_create_backend_user(UserInterface $account) {
  if ($account->hasPermission('administer')) {
    return;
  }

  if (!$profileId = $account->get('field_backend_profile')->value) {
    /** @var Drupal\asu_api\Api\BackendApi\BackendApi $backendApi */
    $backendApi = \Drupal::service('asu_api.backendapi');

    try {
      $userBundle = User::load($account->id())->bundle();
      $type = $userBundle == 'sales' ? 'salesperson' : 'customer';
      $config = \Drupal::config('asu_user.external_user_fields')
        ->get('external_data_map');

      $values = [];

      // If user was created by openid_connect, get user name.
      $session = \Drupal::request()->getSession();
      if ($session->has('first_name') && $session->has('last_name')) {
        $values['first_name'] = $session->get('first_name');
        $values['last_name'] = $session->get('last_name');
      }

      $store = \Drupal::service('tempstore.private')->get('customer');
      foreach ($config as $field => $value) {
        if (!isset($values[$value['external_field']])) {
          $values[$value['external_field']] = $store->get($field) ?? '-';
        }
      }

      $createUser = new CreateUserRequest($account, $values, $type);
      /** @var \Drupal\asu_api\Api\BackendApi\Response\CreateUserResponse $response */
      $response = $backendApi->send($createUser);

      $account->field_backend_profile = $response->getProfileId();
      $account->field_backend_password = $response->getPassword();
      $account->save();
    }
    catch (\Exception $e) {
      \Drupal::logger('asu_user')
        ->critical('Exception while creating backend user:' . $e->getMessage());
    }
  }
}

/**
 * If user has asu_last_application_url set, redirect to application form.
 */
function asu_redirect_on_login_by_session() {
  if ($response = asu_session_check_application_url()) {
    $response->send();
  }
}

/**
 * Get the user data from django backend.
 */
function asu_get_user_external_field_data(UserInterface $account) {
  if ($account->bundle() != 'customer') {
    return;
  }

  // Workaround around issue caused by cache.
  if (!$profileId = $account->field_backend_profile->value) {
    $profileId = asu_get_user_profile_id($account);
    $account->set('field_backend_profile', $profileId);
  }

  try {
    $request = new UserRequest($account);
    $request->setSender($account);

    /** @var \Drupal\asu_api\Api\BackendApi\BackendApi $backendApi */
    $backendApi = \Drupal::service('asu_api.backendapi');
    /** @var \Drupal\asu_api\Api\BackendApi\Response\UserResponse $userResponse */
    $userResponse = $backendApi->send($request);

    $store = \Drupal::service('tempstore.private')->get('customer');
    $config = \Drupal::config('asu_user.external_user_fields')
      ->get('external_data_map');
    StoreHelper::setMultipleValuesToStoreByConfiguration(
      $store,
      $config,
      $userResponse->getUserInformation()
    );
  }
  catch (\Exception $e) {
    \Drupal::logger('asu_backend_api')->emergency('Unable to fetch user information for user: ' . $account->id());
    // @todo add contact form url if there is one.
    \Drupal::messenger()->addWarning(t('We were unable to fetch your personal information.
     If the problem persists contact us.'));
  }
}

/**
 * Implements hook_form_formid_alter().
 */
function asu_user_form_user_customer_form_alter(&$form, FormStateInterface &$form_state) {
  if (in_array('customer', \Drupal::currentUser()->getRoles())) {
    $fieldMap = \Drupal::config('asu_user.external_user_fields')->get('external_data_map');
    $store = \Drupal::service('tempstore.private')->get('customer');
    // If a field value is missing, fetch user information.
    foreach ($fieldMap as $field => $field_data) {
      $form['basic_information'][$field] = [
        '#type' => $field_data['type'],
        '#title' => $field_data['title'],
        '#default_value' => $store->get($field),
      ];
    }
    $form['actions']['submit']['#submit'][] = 'user_edit_submit';
  }
}

/**
 * Additional submit handler for user_form.
 *
 * Update user data to backend.
 */
function user_edit_submit(array $form, FormStateInterface &$form_state) {
  /** @var \Drupal\asu_api\Api\BackendApi\BackendApi $bakendApi */
  $backendApi = \Drupal::service('asu_api.backendapi');
  $user = User::load(\Drupal::currentUser()->id());

  if (!$user->hasRole('customer')) {
    return;
  }

  try {
    $updateRequest = new UpdateUserRequest(
      $user,
      $form_state,
      \Drupal::config('asu_user.external_user_fields')->get('external_data_map')
    );
    $updateRequest->setSender($user);

    /** @var \Drupal\asu_api\Api\BackendApi\Response\UpdateUserResponse $updateUserResponse */
    $updateUserResponse = $backendApi->send($updateRequest);

    $store = \Drupal::service('tempstore.private')->get('customer');
    $config = \Drupal::config('asu_user.external_user_fields')->get('external_data_map');

    $data = $updateUserResponse->getUserInformation();
    foreach ($config as $field => $field_data) {
      $store->set($field, $data[$field_data['external_field']]);
    }
  }
  catch (\Exception $e) {
    \Drupal::logger('asu_user')->critical(
      'authentication failed while updating user information: ' . $e->getMessage()
    );
  }
}

/**
 * Implements hook_entity_base_field_info().
 *
 * Create computed fields dynamically for user entity.
 */
function asu_user_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'customer') {
    $fields = [];
    if ($config = \Drupal::config('asu_user.external_user_fields')) {
      if (!$config->get('external_data_map')) {
        return $fields;
      }
      foreach ($config->get('external_data_map') as $fieldname => $field_data) {
        $fields[$fieldname] = BaseFieldDefinition::create('asu_external_string')
          ->setName($fieldname)
          ->setTranslatable(FALSE)
          ->setLabel(t(
            '@field_label',
            ['@field_label', $field_data['title']]
          ))
          ->setComputed(TRUE)
          ->setClass('\Drupal\asu_user\ExternalData')
          ->setDisplayConfigurable('view', TRUE)
          ->setDisplayOptions('view', [
            'label' => 'visible',
            'weight' => -5,
          ]);
      }
    }
    return $fields;
  }
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function asu_user_field_formatter_info_alter(array &$info) {
  // Used in custom computed field.
  $info['string']['field_types'][] = 'asu_external_string';
}

/**
 * Implements hook_field_widget_info_alter().
 */
function asu_user_field_widget_info_alter(array &$info) {
  // Used in custom computed field.
  $info['string_textfield']['field_types'][] = 'asu_external_string';
}

/**
 * User redirect after user edit form submit.
 */
function _asu_user_user_edit_form_submit($form, &$form_state) {
  $session = \Drupal::request()->getSession();
  if (!$session->get('asu_last_application_url')) {
    $form_state->setRedirect('entity.user.canonical', ['user' => \Drupal::currentUser()->id()]);
  }
}

/**
 * Workaround for first time login cache problem.
 */
function asu_get_user_profile_id(&$account) {
  $profileId = $account->field_backend_profile->value;
  if (!$profileId) {
    $database = \Drupal::database();
    $query = $database->query('SELECT field_backend_profile_value
    FROM user__field_backend_profile
    WHERE entity_id = :userid',
      [':userid' => $account->id()]
    );
    $profileId = NULL;
    if ($results = $query->fetchAll()) {
      foreach ($results as $result) {
        $profileId = $result->field_backend_profile_value;
        return $profileId;
      }
    }
  }
  return $profileId;
}

/**
 * Check if redirect is needed after login or register.
 */
function asu_session_check_application_url(): ?RedirectResponse {
  $session = \Drupal::request()->getSession();
  if ($url = $session->get('asu_last_application_url')) {
    $session->remove('asu_last_application_url');
    return new RedirectResponse(\Drupal::request()->getSchemeAndHttpHost() . $url, 301);
  }
  return NULL;
}

/**
 * Implements hook_entity_operation().
 *
 * Add actions to users list for customers.
 */
function asu_user_entity_operation(EntityInterface $entity) {
  // Add action urls to user entity.
  if (
    $entity instanceof UserInterface &&
    $entity->bundle() == 'customer'
  ) {
    $operations = [];
    $operations['create_application'] = [
      'title' => t('Create an application for user'),
      'url' => Url::fromRoute('asu_application.admin_create_application', ['user_id' => $entity->id()]),
      'weight' => 50,
    ];
    return $operations;
  }
}

/**
 * Customized from Drupal _user_mail_notify function.
 *
 * @param string $op
 *   Which mail to send.
 * @param \Drupal\user\Entity\UserInterface $user
 *   Who to send the mail.
 *
 * @return mixed
 *   Check _user_mail_notify function.
 */
function asu_send_user_email(string $op, UserInterface $account) {
  $params['account'] = $account;
  $langcode = $account->getPreferredLangcode() ?? 'fi';
  // Get the custom site notification email to use as the from email address
  // if it has been set.
  $site_mail = \Drupal::config('system.site')->get('mail_notification');
  // If the custom site notification email has not been set, we use the site
  // default for this.
  if (empty($site_mail)) {
    $site_mail = \Drupal::config('system.site')->get('mail');
  }
  if (empty($site_mail)) {
    $site_mail = ini_get('sendmail_from');
  }
  $mail = \Drupal::service('plugin.manager.mail')->mail('user', $op, $account->getEmail(), $langcode, $params, $site_mail);
  return empty($mail) ? NULL : $mail['result'];
}
