<?php

/**
 * @file
 * Functions to support theming.
 */

use Drupal\Core\Url;
use Drupal\user\Entity\User;

/**
 * Implements hook_preprocess_HOOK().
 */
function asu_user_tools_menu_preprocess_menu(&$variables) {
  if ($variables['menu_name'] == 'user-tools-menu') {
    $current_user = User::load(\Drupal::currentUser()->id());
    $variables['items']['asu_user_tools_menu.user_name']['title'] = $current_user->getEmail();
    $variables['items']['asu_user_tools_menu.user_name']['is_user_tools'] = TRUE;
    $variables['items']['asu_user_tools_menu.user_name']['below']['asu_user_tools_menu.user_information']['url'] = Url::fromRoute('entity.user.canonical', ['user' => \Drupal::currentUser()->id()]);
  }
}
