<?php

namespace Drupal\asu_content\Controller;

use Drupal\Core\Controller\ControllerBase;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 *
 */
class ApartmentContentBulkEditController extends ControllerBase {

  /**
   *
   */
  public function __construct() {
  }

  /**
   *
   */
  public static function create(ContainerInterface $container) {
    // TODO: Change the autogenerated stub.
    return parent::create($container);
  }

  /**
   *
   */
  public function content(Request $request, string $id) {
    return new Response('asd');
  }

}
