on:
  workflow_dispatch:
  repository_dispatch:
    types: [ build_artifact ]
  schedule:
    - cron:  '0 0 * * 0'
name: Build artifacts
env:
  APP_ENV: "test"
  ASU_ELASTICSEARCH_ADDRESS: "http://elastic:9200"
  ASU_ELASTICSEARCH_USERNAME: "test"
  ASU_ELASTICSEARCH_PASSWORD: "pass"
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/city-of-helsinki/drupal-php-docker:8.3-alpine

    services:
      db:
        image: mysql:8
        env:
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
          MYSQL_DATABASE: drupal
          MYSQL_ROOT_PASSWORD: drupal
        ports:
          - 3306:3306

      elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
        env:
          xpack.security.enabled: false
          discovery.type: single-node
        ports:
          - 9200:9200

    steps:
      - uses: actions/checkout@v4

      - name: Build project
        run: composer install --no-interaction

      - name: Setup drupal and save database dump
        continue-on-error: true
        run: |
          drush si -y && drush cr
          drush si --existing-config -y
          drush cim -y
          drush sql-dump --result-file=${GITHUB_WORKSPACE}/latest.sql

      - name: Upload latest database dump
        uses: actions/upload-artifact@v4
        with:
          name: latest.sql
          path: latest.sql
          retention-days: 10
