on: [push]
name: CI
env:
  SIMPLETEST_DB: "mysql://drupal:drupal@db:3306/drupal"
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
  DTT_BASE_URL: "http://127.0.0.1:8080"
  SYMFONY_DEPRECATIONS_HELPER: disabled
  APP_ENV: "test"
  ASU_ELASTICSEARCH_ADDRESS: "http://elastic:9200"
  ASU_ELASTICSEARCH_USERNAME: "test"
  ASU_ELASTICSEARCH_PASSWORD: "pass"
  ASU_DJANGO_BACKEND_URL: "https://django-backend-test-url.fi"
  XDEBUG_MODE: off
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/city-of-helsinki/drupal-php-docker:8.1-alpine

    services:
      db:
        image: mariadb:10.9
        env:
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
          MYSQL_DATABASE: drupal
          MYSQL_ROOT_PASSWORD: drupal
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Build project
        run: composer install

      - name: Run PHPCS
        run: vendor/bin/phpcs public/modules/custom/ --standard=Drupal

      - name: Install Drupal
        run: php -d sendmail_path=$(which true); vendor/bin/drush --yes -v site-install --existing-config --db-url="$SIMPLETEST_DB"

      - name: Start services
        run: |
          drush runserver $SIMPLETEST_BASE_URL > /dev/null 2>&1 &
          chromedriver --port=4444 > /dev/null 2>&1 &
          # Chromium browser is required to run 'functional-javascript' and
          # 'existing-site-javascript' tests.
          chromium-browser --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 &

          # Wait for drush server to start.
          for i in {1..5}; do RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$SIMPLETEST_BASE_URL" || true); if [ "$RESPONSE_CODE" -gt "301" ] || [ "$RESPONSE_CODE" -lt "200" ]; then sleep 2; fi; done

      - name: Run PHPUnit tests
        run: |
          composer test-php public/modules/custom
          [ -d "tests/" ] && composer test-php tests/ || echo "No DTT tests found. Ignoring..."
